#!/bin/bash

# python poetry
export PATH="$HOME/.poetry/env:$PATH"

# rust
export PATH="$HOME/.cargo/bin:$PATH"

# ruby
export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="$PATH/usr/local/bin:/usr/bin:$PATH"
export PATH="$HOME/.rbenv/shims:$PATH"
export PATH="$HOME/.gem/ruby/3.0.0/bin:$PATH" # can remove

# linking rubies to hombrew's openssl 1.1, will break rubies <2.4
# export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"

# conda
export PATH="$HOME/.miniconda3/bin:$PATH"
export PRY=1

# tools for exporting python packages
export PATH="$HOME/.local/bin:$PATH"

# there is some issue with PYTHONPATH between 2 and 3
# we will clear it instead
export PYTHONPATH=""

# Make vim the default editor.
export EDITOR='nvim';

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING='UTF-8';

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';

# Highlight section titles in manual pages.
export LESS_TERMCAP_md="${yellow}";
