#!/bin/bash

# Huge thanks to: webpro/dotfiles
# and to mathiasbynes/dotfiles

# update to Bash 4 as necessary
if ((${BASH_VERSINFO[0]} == 3)); then
	source ~/.dotfiles/tools/bash_4_update
fi

echo Modifying shell
# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don’t want to commit.
for file in ~/.dotfiles/bash/{path,prompt,alias,function}; do
	[ -r $file ] && [ -f $file ] && echo $file && source $file
done;
unset file;

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob;

# Enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
for option in autocd globstar; do
	shopt -s "$option" 2> /dev/null;
done;

# Enable tab completion for `g` by marking it as an alias for `git`
if type _git &> /dev/null && [ -f /usr/local/etc/bash_completion.d/git-completion.bash ]; then
	complete -o default -o nospace -F _git g;
fi;
