#!/bin/bash

# Huge thanks to: webpro/dotfiles
# and to mathiasbynes/dotfiles

# no need to update to bash 4 since
# we will be moving to zsh
# update to Bash 4 as necessary
# if ((${BASH_VERSINFO[0]} == 3)); then
# 	source ~/.dotfiles/tools/bash_4_update
# fi

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don’t want to commit.
for file in ~/.dotfiles/shell/{path,alias,function}; do
	[ -r $file ] && [ -f $file ] && source $file
done;
unset file;

# check to see if zsh has been install correctly
# if it has, ignore prompt, else source ~/.dotfiles/shell/bash_prompt
if hash zsh 2>/dev/null; then
	sudo chsh /usr/local/bin/zsh
else
	source ~/.dotfiles/shell/bash_prompt
fi
