#!/bin/bash

_get_brew() {
    if hash brew 2>/dev/null; then
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi
}

_get_brew()
brew update
brew cleanup

# https://medium.com/@webprolific/getting-started-with-dotfiles-43c3602fd789
brew tap caskroom/cask
brew tap caskroom/versions

# when we install ctags we have to remove the earlier link
brew unlink ctags
brew install --HEAD universal-ctags/universal-ctags/universal-ctags

# we will install zsh but won't switch to it here
brew install zsh
if ! grep -q /usr/local/bin/zsh /private/etc/shells; then
	echo /usr/local/bin/zsh | sudo tee -a /private/etc/shells
else
	echo 'zsh already found in /private/etc/shells'
fi

# others
brew install wget

# macOS applications
brew cask install iterm2
brew cask install atom
brew cask install dropbox
brew cask install google-chrome
brew cask install vlc
brew cask install bettertouchtool # you'll need to provide the key for this
brew cask install slack
brew cask install apptivate

# setups
# copy over the fonts
cp -r $HOME/dotfiles/themes/FiraCode $HOME/Library/Fonts


