#!/bin/bash

sudo apt-get install zsh

# make sure to install Oh-My-Zsh!
sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

sudo apt-get install neovim

# to install GNU global
sudo apt-get update
sudo apt-get -y install curl
sudo apt-get -y install wget
sudo apt-get -y install ncurses-dev
sudo apt-get -y install exuberant-ctags

sudo apt-get -y install python

CURRENT=`pwd`
wget http://tamacom.com/global/global-6.4.tar.gz
tar zxvf global-6.4.tar.gz
cd global-6.4
./configure
make
sudo make install

# GNU global cleanup
cd $CURRENT
rm -rf global-6.4
rm global-6.4.tar.gz

sudo apt-get -y install tmux
sudo apt-get -y install python3

# modify the gnome color theme with Mayccoll/Gogh
# uses gruvbox dark
sudo apt-get install dconf-cli
wget -O xt https://git.io/v7eBS && chmod +x xt && ./xt && rm xt


