#!/bin/bash

# Install Bash 4 using homebrew
brew install bash

# Add the new shell to the list of legit shells if not in /private/etc/shells
if ! grep -q /usr/local/bin/bash /private/etc/shells; then
    echo /usr/local/bin/bash | sudo tee -a /private/etc/shells
else
    echo '/usr/local/bin/bash already found in /private/etc/shells'
fi

# Change the shell for the user
chsh -s /usr/local/bin/bash

# Restart terminal.app (new window works too)

# Check for Bash 4 and /usr/local/bin/bash...
echo $BASH && echo $BASH_VERSION
