#!/usr/bin/env bash

# run synergy
# cd /Applications/Synergy.app/Contents/Resources
# ./synergy-core --server
# if no config path is set, it will look at ~/.synergy.conf

# Build and flash the Planck with what ever is in the folder
build_planck() {
  cd $WORKSPACE/olkb/qmk_firmware
  make planck-rev4-derek-all
  echo "build complete. reset the planck and run #flash_planck" 
}

flash_planck() {
  dfu-programmer atmega32u4 erase --force
  cd $WORKSPACE/olkb/qmk_firmware/.build

  # in some certain cases, you may need to clear eeprom if the chicken
  # is well and truly cooked. For that you use
  # dfu-programmer atmega32u4 flash --eeprom $workspace/olkb/qmk_firmware/quantum/tools/eeprom_reset.hex
  # then reset and reflash. That should do the trick

  dfu-programmer atmega32u4 flash planck_rev4_derek.hex
}

planck() {
  local location="$WORKSPACE/olkb/qmk_firmware/keyboards/planck/keymaps/derek"
  sed -n '/QWERTY_BEGIN/,/QWERTY_END/p' "$location/keymap.c"
  sed -n '/LOWER_BEGIN/,/LOWER_END/p' "$location/keymap.c"
  sed -n '/RAISE_BEGIN/,/RAISE_END/p' "$location/keymap.c"
  sed -n '/ADJUST_BEGIN/,/ADJUST_END/p' "$location/keymap.c"
  cd $location
}
