#!/usr/bin/env bash

# ruby
export PATH="$HOME/.rbenv/bin:$PATH"
export PRY=1

# there is some issue with PYTHONPATH between 2 and 3
# we will clear it instead
export PYTHONPATH=""

# Make vim the default editor.
export EDITOR='vim';

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING='UTF-8';

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';

# Highlight section titles in manual pages.
export LESS_TERMCAP_md="${yellow}";
